import Head from 'next/head'
import Image from 'next/image'
import { motion, useCycle } from 'framer-motion'
import styles from '../styles/Home.module.css'
import Button from '../components/button'
import Sidemenu from '../components/sidemenu'
import Console from '../components/console'

const variants = {
	open: {
		opacity: 1,
		x: 0,
		display: 'block',
		transition: {
			duration: 0.2,
		},
	},
	closed: {
		opacity: 0,
		x: '-100%',
		display: 'none',
		transition: {
			duration: 0.2,
			display: {
				delay: 0.2,
			},
		},
	},
}

export default function Home() {
	const [animation, cycleAnimation] = useCycle(false, true)

	return (
		<div>
			<Head>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/MutsukiHyperStare.ico' />
				<title>VSmusic</title>
			</Head>

			<div className={styles.main}>
				<motion.nav className={styles.sidebar} animate={animation ? 'open' : 'closed'} initial={false} variants={variants}>
					<Sidemenu />
				</motion.nav>

				<main className={styles.container}>
					<Button toggle={() => cycleAnimation()} />

					<motion.div drag>
						<Console />
					</motion.div>
				</main>
			</div>

			<footer className={styles.footer}>
				<a href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app' target='_blank' rel='noopener noreferrer'>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}
