import Head from 'next/head'
import Image from 'next/image'
import { motion, useCycle } from 'framer-motion'
import styles from '../styles/Home.module.css'

const variants = {
	open: {
		opacity: 1,
		x: 0,
		transition: {
			duration: 0.5,
			type: 'spring',
		},
	},
	closed: {
		opacity: 0,
		x: '-100%',
		transition: {
			duration: 0.5,
			type: 'spring',
		},
	},
}

export default function Home() {
	const [animation, cycleAnimation] = useCycle('open', 'closed')

	return (
		<div className={styles.container}>
			<Head>
				<title>Application</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<h4 style={{ textAlign: 'center' }}>Testing Page For Deployment, Framer-motion Animations, Resposive Page/Web Design, Cross-platform Compatibility.</h4>

			<main className={styles.main}>
				<motion.div animate={animation} variants={variants}>
					<h2 className={styles.title}>Animation Target</h2>
				</motion.div>

				<motion.p className={styles.description} onClick={() => cycleAnimation()} whileTap={{ scale: 0.9 }}>
					Click/Tap me to initiate the animation
				</motion.p>

				<div className={styles.grid}>
					<a href='https://nextjs.org/docs' className={styles.card}>
						<h2>Documentation &rarr;</h2>
						<p>Find in-depth information about Next.js features and API.</p>
					</a>

					<a href='https://nextjs.org/learn' className={styles.card}>
						<h2>Learn &rarr;</h2>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</a>

					<a href='https://github.com/vercel/next.js/tree/canary/examples' className={styles.card}>
						<h2>Examples &rarr;</h2>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</a>

					<a href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app' className={styles.card}>
						<h2>Deploy &rarr;</h2>
						<p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
					</a>
				</div>
			</main>

			<footer className={styles.footer}>
				<a href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app' target='_blank' rel='noopener noreferrer'>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}
